=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/SPCmdletSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
     xmlns="urn:Microsoft.SharePoint.PowerShell"
     elementFormDefault="qualified"
     targetNamespace="urn:Microsoft.SharePoint.PowerShell">

  <xs:element name="Config" type="ConfigType"/>

  <xs:complexType name="ConfigType">
    <xs:sequence>
      <xs:element name="Assembly" type="AssemblyType" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AssemblyType">
    <xs:sequence>
      <xs:element name="Cmdlet" type="CmdletType" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="CmdletType">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="VerbName" type="xs:string" />
      <xs:element name="ClassName" type="xs:string" />
      <xs:element name="HelpFile" type="xs:string" />
      <xs:element name="FeatureDependencyId" type="xs:string" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/MetadataCmdlets.xml
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">

  <ps:Assembly Name="Microsoft.SharePoint.Taxonomy, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
    <ps:Cmdlet>
      <ps:VerbName>Get-SPTaxonomySession</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletGetTaxonomySession</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPMetadataServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletNewMetadataService</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>   
    <ps:Cmdlet>
      <ps:VerbName>Get-SPMetadataServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletGetMetadataService</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>    
    <ps:Cmdlet>
      <ps:VerbName>Set-SPMetadataServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletSetMetadataService</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPMetadataServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletNewMetadataServiceProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>   
    <ps:Cmdlet>
      <ps:VerbName>Get-SPMetadataServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletGetMetadataServiceProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>    
    <ps:Cmdlet>
      <ps:VerbName>Set-SPMetadataServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletSetMetadataServiceProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Export-SPMetadataWebServicePartitionData</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletExportMetadataWebServicePartitionData</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Import-SPMetadataWebServicePartitionData</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletImportMetadataWebServicePartitionData</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Clear-SPMetadataWebServicePartitionData</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletClearMetadataWebServicePartitionData</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>  
    <ps:Cmdlet>
      <ps:VerbName>Get-SPSiteSubscriptionMetadataConfig</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletGetSiteSubscriptionMetadataConfig</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPSiteSubscriptionMetadataConfig</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletRemoveSiteSubscriptionMetadataConfig</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPSiteSubscriptionMetadataConfig</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Cmdlet.SPCmdletSetSiteSubscriptionMetadataConfig</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>    
    <ps:Cmdlet>
      <ps:VerbName>Copy-SPTaxonomyGroups</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Hybrid.Cmdlet.SPCmdletMigrateSPTaxonomyGroups</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Stop-SPTaxonomyReplication</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Hybrid.Cmdlet.SPCmdletStopSPTaxonomyReplication</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Copy-SPContentTypes</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Hybrid.Cmdlet.SPCmdletMigrateSPContentTypes</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Stop-SPContentTypeReplication</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Taxonomy.Hybrid.Cmdlet.SPCmdletStopSPContentTypeReplication</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Taxonomy.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
  </ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/ppsmonitoringcmdlet.xml
<?xml version="1.0" encoding="utf-8" ?>
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">

  <ps:Assembly Name="Microsoft.PerformancePoint.Scorecards.BIMonitoringService, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
    <ps:Cmdlet>
      <ps:VerbName>New-SPPerformancePointServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.NewSPPerformancePointMonitoringServiceApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPPerformancePointServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.GetSPPerformancePointMonitoringServiceApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPPerformancePointServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.SetSPPerformancePointMonitoringServiceApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPPerformancePointServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.RemoveSPPerformancePointMonitoringServiceApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPPerformancePointServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.NewSPPerformancePointMonitoringServiceApplicationProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPPerformancePointServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.RemoveSPPerformancePointMonitoringServiceApplicationProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPPerformancePointSecureDataValues</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.SetSPPerformancePointSecureDataValues</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPPerformancePointServiceApplicationTrustedLocation</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.NewSPPerformancePointMonitoringServiceApplicationTrustedLocation</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPPerformancePointServiceApplicationTrustedLocation</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.GetSPPerformancePointMonitoringServiceApplicationTrustedLocation</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPPerformancePointServiceApplicationTrustedLocation</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.RemoveSPPerformancePointMonitoringServiceApplicationTrustedLocation</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Clear-SPPerformancePointServiceApplicationTrustedLocation</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.ClearSPPerformancePointMonitoringServiceApplicationTrustedLocation</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Export-SPPerformancePointContent</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.ExportSPPerformancePointContent</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Import-SPPerformancePointContent</ps:VerbName>
      <ps:ClassName>Microsoft.PerformancePoint.Scorecards.ImportSPPerformancePointContent</ps:ClassName>
      <ps:HelpFile>Microsoft.PerformancePoint.Scorecards.BIMonitoringService.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
</ps:Assembly>

</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/ECMCmdlet.xml
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">

  <ps:Assembly Name="Microsoft.SharePoint.Publishing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
    <ps:Cmdlet>
      <ps:VerbName>New-SPContentDeploymentPath</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletNewContentDeploymentPath</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPContentDeploymentPath</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletGetContentDeploymentPath</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPContentDeploymentPath</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletSetContentDeploymentPath</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPContentDeploymentPath</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletRemoveContentDeploymentPath</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPContentDeploymentJob</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletNewContentDeploymentJob</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPContentDeploymentJob</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletGetContentDeploymentJob</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPContentDeploymentJob</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletSetContentDeploymentJob</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Start-SPContentDeploymentJob</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletStartContentDeploymentJob</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPContentDeploymentJob</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletRemoveContentDeploymentJob</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPSiteSubscriptionEdiscoveryHub</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletSetSiteSubscriptionEdiscoveryHub</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
     <ps:Cmdlet>
      <ps:VerbName>Get-SPSiteSubscriptionEdiscoveryHub</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletGetSiteSubscriptionEdiscoveryHub</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPSiteSubscriptionEdiscoverySearchScope</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.Publishing.Cmdlet.SPCmdletGetSiteSubscriptionEdiscoverySearchScope</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.Publishing.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>

  </ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/visioservicecmdlets.xml
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">
  <ps:Assembly Name="Microsoft.Office.Visio.Server, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
    <ps:Cmdlet>
      <ps:VerbName>Get-SPVisioPerformance</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.GetSPVisioPerformance</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPVisioPerformance</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.SetSPVisioPerformance</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPVisioExternalData</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.GetSPVisioExternalData</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPVisioExternalData</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.SetSPVisioExternalData</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPVisioSafeDataProvider</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.GetSPVisioSafeDataProvider</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPVisioSafeDataProvider</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.SetSPVisioSafeDataProvider</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPVisioSafeDataProvider</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.RemoveSPVisioSafeDataProvider</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPVisioSafeDataProvider</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.NewSPVisioSafeDataProvider</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPVisioServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.GetSPVisioServiceApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPVisioServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.SetSPVisioServiceApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPVisioServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.NewSPVisioServiceApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPVisioServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.GetSPVisioServiceApplicationProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPVisioServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Visio.Server.Cmdlet.NewSPVisioServiceApplicationProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Visio.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>5FE8E789-D1B7-44B3-B634-419C531CFDCA</ps:FeatureDependencyId>
    </ps:Cmdlet>
  </ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/WordServerCmdlets.xml
<?xml version='1.0'?>
<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell SPCmdletSchema.xsd">
	<ps:Assembly Name="Microsoft.Office.Word.Server, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
		<ps:Cmdlet>
			<ps:VerbName>Set-SPWordConversionServiceApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Word.Server.Powershell.ServiceAppSet</ps:ClassName>
			<ps:HelpFile>Microsoft.Office.Word.Server.dll-Help.xml</ps:HelpFile>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>New-SPWordConversionServiceApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Word.Server.Powershell.ServiceAppNew</ps:ClassName>
			<ps:HelpFile>Microsoft.Office.Word.Server.dll-Help.xml</ps:HelpFile>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Remove-SPWordConversionServiceJobHistory</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Word.Server.Powershell.JobHistoryRemove</ps:ClassName>
			<ps:HelpFile>Microsoft.Office.Word.Server.dll-Help.xml</ps:HelpFile>
		</ps:Cmdlet>
	</ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/TranslationServicesCmdlets.xml
<?xml version='1.0'?>
<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell SPCmdletSchema.xsd">
	<ps:Assembly Name="Microsoft.Office.TranslationServices, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
		<ps:Cmdlet>
			<ps:VerbName>Set-SPTranslationServiceApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.TranslationServices.Powershell.TranslationServiceApplicationSet</ps:ClassName>
			<ps:HelpFile>Microsoft.Office.TranslationServices.dll-Help.xml</ps:HelpFile>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>New-SPTranslationServiceApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.TranslationServices.Powershell.TranslationServiceApplicationNew</ps:ClassName>
			<ps:HelpFile>Microsoft.Office.TranslationServices.dll-Help.xml</ps:HelpFile>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Set-SPTranslationServiceApplicationProxy</ps:VerbName>
			<ps:ClassName>Microsoft.Office.TranslationServices.Powershell.TranslationServiceApplicationProxySet</ps:ClassName>
			<ps:HelpFile>Microsoft.Office.TranslationServices.dll-Help.xml</ps:HelpFile>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>New-SPTranslationServiceApplicationProxy</ps:VerbName>
			<ps:ClassName>Microsoft.Office.TranslationServices.Powershell.TranslationServiceApplicationProxyNew</ps:ClassName>
			<ps:HelpFile>Microsoft.Office.TranslationServices.dll-Help.xml</ps:HelpFile>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Remove-SPTranslationServiceJobHistory</ps:VerbName>
			<ps:ClassName>Microsoft.Office.TranslationServices.Powershell.TranslationJobHistoryRemove</ps:ClassName>
			<ps:HelpFile>Microsoft.Office.TranslationServices.dll-Help.xml</ps:HelpFile>
		</ps:Cmdlet>
	</ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/TranslationCmdlets.xml
<?xml version='1.0'?>
<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell SPCmdletSchema.xsd">
    <ps:Assembly Name="Microsoft.SharePoint.Translation, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
        <ps:Cmdlet>
            <ps:VerbName>Set-SPTranslationThrottlingSetting</ps:VerbName>
            <ps:ClassName>Microsoft.SharePoint.Translation.Powershell.TranslationThrottlingSettingsSet</ps:ClassName>
            <ps:HelpFile>Microsoft.SharePoint.Translation.dll-Help.xml</ps:HelpFile>
        </ps:Cmdlet>
        <ps:Cmdlet>
            <ps:VerbName>Get-SPTranslationThrottlingSetting</ps:VerbName>
            <ps:ClassName>Microsoft.SharePoint.Translation.Powershell.TranslationThrottlingSettingsGet</ps:ClassName>
            <ps:HelpFile>Microsoft.SharePoint.Translation.dll-Help.xml</ps:HelpFile>
        </ps:Cmdlet>
    </ps:Assembly>
</ps:Config>
