=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/SPCmdletSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
     xmlns="urn:Microsoft.SharePoint.PowerShell"
     elementFormDefault="qualified"
     targetNamespace="urn:Microsoft.SharePoint.PowerShell">

  <xs:element name="Config" type="ConfigType"/>

  <xs:complexType name="ConfigType">
    <xs:sequence>
      <xs:element name="Assembly" type="AssemblyType" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AssemblyType">
    <xs:sequence>
      <xs:element name="Cmdlet" type="CmdletType" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="CmdletType">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="VerbName" type="xs:string" />
      <xs:element name="ClassName" type="xs:string" />
      <xs:element name="HelpFile" type="xs:string" />
      <xs:element name="FeatureDependencyId" type="xs:string" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/MOSSUpgradeSSOCmdlet.xml
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">

  <ps:Assembly Name="Microsoft.Office.SecureStoreService, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
    <ps:Cmdlet>
      <ps:VerbName>Upgrade-SPSingleSignOnDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.UpgradeCommand</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Disable-SPSingleSignOn</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.DisableServiceCommand</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPSecureStoreServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPNewSecureStoreServiceApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPSecureStoreServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPSetSecureStoreServiceApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPSecureStoreServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPNewSecureStoreServiceApplicationProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>

    <ps:Cmdlet>
      <ps:VerbName>Clear-SPSecureStoreCredentialMapping</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPClearSPSecureStoreCredentialMapping</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPSecureStoreApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPGetSPSecureStoreApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPSecureStoreApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPNewSPNewSPSecureStoreApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPSecureStoreApplicationField</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPNewSPNewSPSecureStoreTargetApplicationField</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>New-SPSecureStoreTargetApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPNewSPNewSPSecureStoreTargetApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPSecureStoreApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPRemoveSPSecureStoreApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPSecureStoreApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPSetSPSecureStoreApplication</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Update-SPSecureStoreCredentialMapping</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPUpdateSPSecureStoreCredentialMapping</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Update-SPSecureStoreGroupCredentialMapping</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPUpdateSPSecureStoreGroupCredentialMapping</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>

    <ps:Cmdlet>
      <ps:VerbName>Update-SPSecureStoreApplicationServerKey</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPUpdateSPSecureStoreApplicationServerKey</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Update-SPSecureStoreMasterKey</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPUpdateSPSecureStoreMasterKey</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>

    <ps:Cmdlet>
      <ps:VerbName>Set-SPSecureStoreDefaultProvider</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPSetSPSecureStoreDefaultProvider</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Clear-SPSecureStoreDefaultProvider</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPClearSPSecureStoreDefaultProvider</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>

    <ps:Cmdlet>
      <ps:VerbName>Add-SPSecureStoreSystemAccount</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPAddSPSecureStoreSystemAccount</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPSecureStoreSystemAccount</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPGetSPSecureStoreSystemAccount</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>

    <ps:Cmdlet>
    <ps:VerbName>Remove-SPSecureStoreSystemAccount</ps:VerbName>
      <ps:ClassName>Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPRemoveSecureStoreSystemAccount</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml</ps:HelpFile>
    </ps:Cmdlet>

  </ps:Assembly>

</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/NintexExternalPlatformCmdlets.xml
<?xml version="1.0" encoding="utf-8" ?>
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">
  <ps:Assembly Name="Nintex.Live.SharePoint, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c52d764dcf7ec883">
    <ps:Cmdlet>
      <ps:VerbName>Install-ExternalPlatform</ps:VerbName>
      <ps:ClassName>Nintex.Live.SharePoint.PowerShell.Install</ps:ClassName>
      <ps:HelpFile>Nintex.Live.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Uninstall-ExternalPlatform</ps:VerbName>
      <ps:ClassName>Nintex.Live.SharePoint.PowerShell.Uninstall</ps:ClassName>
      <ps:HelpFile>Nintex.Live.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
  </ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/PowerPointCmdlets.xml
<?xml version='1.0'?>
<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell SPCmdletSchema.xsd">
    <ps:Assembly Name="Microsoft.Office.Server.Powerpoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
        <ps:Cmdlet>
            <ps:VerbName>Set-SPPowerPointConversionServiceApplication</ps:VerbName>
            <ps:ClassName>Microsoft.Office.Server.PowerPoint.PowerShell.SetSPPowerPointConversionServiceApplication</ps:ClassName>
            <ps:HelpFile>Microsoft.Office.Server.Powerpoint.dll-Help.xml</ps:HelpFile>
        </ps:Cmdlet>
        <ps:Cmdlet>
            <ps:VerbName>New-SPPowerPointConversionServiceApplication</ps:VerbName>
            <ps:ClassName>Microsoft.Office.Server.PowerPoint.PowerShell.NewSPPowerPointConversionServiceApplication</ps:ClassName>
            <ps:HelpFile>Microsoft.Office.Server.Powerpoint.dll-Help.xml</ps:HelpFile>
        </ps:Cmdlet>
        <ps:Cmdlet>
            <ps:VerbName>New-SPPowerPointConversionServiceApplicationProxy</ps:VerbName>
            <ps:ClassName>Microsoft.Office.Server.PowerPoint.PowerShell.NewSPPowerPointConversionServiceApplicationProxy</ps:ClassName>
            <ps:HelpFile>Microsoft.Office.Server.Powerpoint.dll-Help.xml</ps:HelpFile>
        </ps:Cmdlet>
    </ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/WorkflowSolutionsCmdlet.xml
<ps:Config
    xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell SPCmdletSchema.xsd">
  <ps:Assembly Name="Microsoft.SharePoint.WorkflowServices, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
    <ps:Cmdlet>
      <ps:VerbName>New-SPWorkflowServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.WorkflowServices.PowerShell.NewSPWorkflowServiceApplicationProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.WorkflowServices.PowerShell.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPWorkflowServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.WorkflowServices.PowerShell.GetSPWorkflowServiceApplicationProxy</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.WorkflowServices.PowerShell.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Copy-SPActivitiesToWorkflowService</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.WorkflowServices.PowerShell.CopySPActivitiesToWorkflowService</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.WorkflowServices.PowerShell.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
	<ps:Cmdlet>
      <ps:VerbName>Register-SPWorkflowService</ps:VerbName>
      <ps:ClassName>Microsoft.SharePoint.WorkflowServices.PowerShell.RegisterSPWorkflowService</ps:ClassName>
      <ps:HelpFile>Microsoft.SharePoint.WorkflowServices.PowerShell.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
  </ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/NintexFormsCmdlets.xml
<?xml version="1.0" encoding="utf-8" ?>
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">
  <ps:Assembly Name="Nintex.Forms.SharePoint, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c52d764dcf7ec883">
    <ps:Cmdlet>
      <ps:VerbName>Install-NFService</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.Install</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Upgrade-NFService</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.Upgrade</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Add-InlineFunction</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.AddInlineFunctionCommand</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-InlineFunction</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.RemoveInlineFunctionCommand</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Show-InlineFunctions</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.ShowInlineFunctionsCommand</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Show-RuntimeFunctions</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.ShowRuntimeFunctionsCommand</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Add-FormControl</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.AddFormControlCommand</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Update-NFSiteId</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.UpdateSiteIdCommand</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-FormControl</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.RemoveFormControlCommand</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Deactivate-NFOrphanedLiveAndMobileForms</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.DeactivateOrphanedLiveAndMobileForms</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Update-NFLicense</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.UpdateLicense</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Create-NFDatabase</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.CreateDatabase</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Update-NFMobileRelay</ps:VerbName>
      <ps:ClassName>Nintex.Forms.SharePoint.PowerShell.Commands.UpdateMobileRelay</ps:ClassName>
      <ps:HelpFile>Nintex.Forms.PowerShell.Commands.HelpFile.xml</ps:HelpFile>
    </ps:Cmdlet>
  </ps:Assembly>
</ps:Config>
