=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/SPCmdletSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
     xmlns="urn:Microsoft.SharePoint.PowerShell"
     elementFormDefault="qualified"
     targetNamespace="urn:Microsoft.SharePoint.PowerShell">

  <xs:element name="Config" type="ConfigType"/>

  <xs:complexType name="ConfigType">
    <xs:sequence>
      <xs:element name="Assembly" type="AssemblyType" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AssemblyType">
    <xs:sequence>
      <xs:element name="Cmdlet" type="CmdletType" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="CmdletType">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="VerbName" type="xs:string" />
      <xs:element name="ClassName" type="xs:string" />
      <xs:element name="HelpFile" type="xs:string" />
      <xs:element name="FeatureDependencyId" type="xs:string" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/IpfsCmdlet.xml
<?xml version="1.0" encoding="utf-8"?>
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">
  <ps:Assembly Name="Microsoft.Office.InfoPath.Server, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
    <ps:Cmdlet>
      <ps:VerbName>Get-SPInfoPathFormsService</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.GetFormsServiceCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPInfoPathFormsService</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.SetFormsServiceCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.GetFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.SetFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Install-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.InstallFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>A10B6AA4-135D-4598-88D1-8D4FF5691D13</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Uninstall-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.UninstallFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>A10B6AA4-135D-4598-88D1-8D4FF5691D13</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Enable-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.EnableFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>A10B6AA4-135D-4598-88D1-8D4FF5691D13</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Disable-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.DisableFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
      <ps:FeatureDependencyId>A10B6AA4-135D-4598-88D1-8D4FF5691D13</ps:FeatureDependencyId>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Start-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.StartFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Stop-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.StopFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Update-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.UpdateFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Test-SPInfoPathFormTemplate</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.TestFormTemplateCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPDataConnectionFile</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.GetDataConnectionFileCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPDataConnectionFile</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.SetDataConnectionFileCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Install-SPDataConnectionFile</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.InstallDataConnectionFileCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Uninstall-SPDataConnectionFile</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.UninstallDataConnectionFileCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPDataConnectionFileDependent</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.GetDataConnectionFileDependentCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPInfoPathWebServiceProxy</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.GetWebServiceProxyCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPInfoPathWebServiceProxy</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.SetWebServiceProxyCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPInfoPathUserAgent</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.GetUserAgentCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Add-SPInfoPathUserAgent</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.AddUserAgentCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPInfoPathUserAgent</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.RemoveUserAgentCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Update-SPInfoPathAdminFileUrl</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.RepairUtilities.UpdateInfoPathAdminFileUrlCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Export-SPInfoPathAdministrationFiles</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.ExportFormsServiceAdminFiles</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Import-SPInfoPathAdministrationFiles</ps:VerbName>
      <ps:ClassName>Microsoft.Office.InfoPath.Server.Cmdlet.ImportFormsServiceAdminFiles</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.InfoPath.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
  </ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/accessservicessvccmdlets.xml
<?xml version='1.0'?>
<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell SPCmdletSchema.xsd">
	<ps:Assembly Name="Microsoft.Office.Access.Services.Moss, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
		<ps:Cmdlet>
			<ps:VerbName>Get-SPAccessServicesApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.GetSPAccessServicesApplication</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Set-SPAccessServicesApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.SetSPAccessServicesApplication</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>New-SPAccessServicesApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.NewSPAccessServicesApplication</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>New-SPAccessServicesApplicationProxy</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.NewSPAccessServicesApplicationProxy</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Get-SPAccessServicesDatabaseServer</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.GetSPAccessServicesDatabaseServer</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>New-SPAccessServicesDatabaseServer</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.NewSPAccessServicesDatabaseServer</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Set-SPAccessServicesDatabaseServer</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.SetSPAccessServicesDatabaseServer</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Get-SPAccessServicesDatabase</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.GetSPAccessServicesDatabase</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Reset-SPAccessServicesDatabasePassword</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.ResetSPAccessServicesDatabasePassword</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Get-SPAccessServicesDatabaseServerGroup</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.GetSPAccessServicesDatabaseServerGroup</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Get-SPAccessServicesDatabaseServerGroupMapping</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.GetSPAccessServicesDatabaseServerGroupMapping</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Set-SPAccessServicesDatabaseServerGroupMapping</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.SetSPAccessServicesDatabaseServerGroupMapping</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Remove-SPAccessServicesDatabaseServer</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.RemoveSPAccessServicesDatabaseServer</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Copy-SPAccessServicesDatabaseCredentials</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.CopySPAccessServicesDatabaseCredentials</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Import-SPAccessServicesDatabase</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.ImportSPAccessServicesDatabase</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Export-SPAccessServicesDatabase</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Services.PowerShell.ExportSPAccessServicesDatabase</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.server.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>5094E988-524B-446c-B2F6-040B5BE46297</ps:FeatureDependencyId>
		</ps:Cmdlet>
	</ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/OfficeServerCmdlets.xml
<?xml version="1.0" encoding="utf-8"?>
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">
  <ps:Assembly Name="Microsoft.Office.Server, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">

    <ps:Cmdlet>
      <ps:VerbName>Get-SPSessionStateService</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.GetSessionStateServiceCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPSessionStateService</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SetSessionStateServiceCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Enable-SPSessionStateService</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.EnableSessionStateServiceCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Disable-SPSessionStateService</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.DisableSessionStateServiceCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>

    <ps:Cmdlet>
      <ps:VerbName>New-SPStateServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.NewStateServiceApplicationCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPStateServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.GetStateServiceApplicationCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPStateServiceApplication</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SetStateServiceApplicationCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>

    <ps:Cmdlet>
      <ps:VerbName>New-SPStateServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.NewStateServiceApplicationProxyCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPStateServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.GetStateServiceApplicationProxyCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPStateServiceApplicationProxy</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SetStateServiceApplicationProxyCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>

    <ps:Cmdlet>
      <ps:VerbName>New-SPStateServiceDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.NewStateServiceDatabaseCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPStateServiceDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.RemoveStateServiceDatabaseCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPStateServiceDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.GetStateServiceDatabaseCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPStateServiceDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SetStateServiceDatabaseCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Mount-SPStateServiceDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.MountStateServiceDatabaseCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Dismount-SPStateServiceDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.DismountStateServiceDatabaseCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Initialize-SPStateServiceDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.InitializeStateServiceDatabaseCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Suspend-SPStateServiceDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SuspendStateServiceDatabaseCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Resume-SPStateServiceDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.ResumeStateServiceDatabaseCmdlet</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Split-SPServerScaleOutDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletSplitScaleOutDatabase</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPServerScaleOutDatabaseDataState</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletGetScaleOutDatabaseDataState</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPServerScaleOutDatabaseDataSubRange</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletSetScaleOutDatabaseDataSubRange</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Set-SPServerScaleOutDatabaseDataRange</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletSetScaleOutDatabaseDataRange</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Clear-SPServerScaleOutDatabaseDeletedDataSubRange</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletClearScaleOutDatabaseDeleteDataSubRange</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPServerScaleOutDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletGetScaleOutDatabase</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPServerScaleOutDatabaseLogEntry</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletGetScaleOutDatabaseLogEntry</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Clear-SPServerScaleOutDatabaseLog</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletClearScaleOutDatabaseLog</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Get-SPServerScaleOutDatabaseInconsistency</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletGetScaleOutDatabaseInconsistency</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Export-SPServerScaleOutDatabaseTenantData</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletScaleOutDatabaseTenantDataExport</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Import-SPServerScaleOutDatabaseTenantData</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletScaleOutDatabaseTenantDataImport</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Clear-SPServerScaleOutDatabaseTenantData</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletScaleOutDatabaseTenantDataClear</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Add-SPServerScaleOutDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletAddScaleOutDatabase</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>Remove-SPServerScaleOutDatabase</ps:VerbName>
      <ps:ClassName>Microsoft.Office.Server.Administration.SPCmdletRemoveScaleOutDatabase</ps:ClassName>
      <ps:HelpFile>Microsoft.Office.Server.dll-help.xml</ps:HelpFile>
    </ps:Cmdlet>
  </ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/accessservicescmdlets.xml
<?xml version='1.0'?>
<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell SPCmdletSchema.xsd">
	<ps:Assembly Name="Microsoft.Office.Access.Server, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
		<ps:Cmdlet>
			<ps:VerbName>Get-SPAccessServiceApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Server.PowerShell.GetSPAccessServiceApplication</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.services.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>1CC4B32C-299B-41aa-9770-67715EA05F25</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>Set-SPAccessServiceApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Server.PowerShell.SetSPAccessServiceApplication</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.services.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>1CC4B32C-299B-41aa-9770-67715EA05F25</ps:FeatureDependencyId>
		</ps:Cmdlet>
		<ps:Cmdlet>
			<ps:VerbName>New-SPAccessServiceApplication</ps:VerbName>
			<ps:ClassName>Microsoft.Office.Access.Server.PowerShell.NewSPAccessServiceApplication</ps:ClassName>
			<ps:HelpFile>microsoft.office.access.services.dll-help.xml</ps:HelpFile>
			<ps:FeatureDependencyId>1CC4B32C-299B-41aa-9770-67715EA05F25</ps:FeatureDependencyId>
		</ps:Cmdlet>
	</ps:Assembly>
</ps:Config>

=== amalinpf/WindowsPowerShell/MyPOWERSHELL/Registration/NintexConnectorWorkflowCmdlet.xml
<?xml version="1.0" encoding="utf-8"?>
<ps:Config xmlns:ps="urn:Microsoft.SharePoint.PowerShell"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="urn:Microsoft.SharePoint.PowerShell  SPCmdletSchema.xsd">
  <ps:Assembly Name="Nintex.Workflow.Live, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bd539bd4aa1e2820">
    <ps:Cmdlet>
      <ps:VerbName>Install-ExternalConnector</ps:VerbName>
      <ps:ClassName>Nintex.Workflow.Live.PowerShell.CmdletInstallService</ps:ClassName>
      <ps:HelpFile></ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>UnInstall-ExternalConnector</ps:VerbName>
      <ps:ClassName>Nintex.Workflow.Live.PowerShell.CmdletUnInstallService</ps:ClassName>
      <ps:HelpFile></ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>UpdateSiteMappings-ExternalConnector</ps:VerbName>
      <ps:ClassName>Nintex.Workflow.Live.PowerShell.CmdletUpdateSiteMappings</ps:ClassName>
      <ps:HelpFile></ps:HelpFile>
    </ps:Cmdlet>
    <ps:Cmdlet>
      <ps:VerbName>SyncServices-ExternalConnector</ps:VerbName>
      <ps:ClassName>Nintex.Workflow.Live.PowerShell.CmdletSyncServices</ps:ClassName>
      <ps:HelpFile></ps:HelpFile>
    </ps:Cmdlet>
  </ps:Assembly>
</ps:Config>
